### ISSUE TITLE
installation fatal error 'openssl/ssl.h' file not found

### ISSUE THREAD

**Issue by kjran** [icebert/pblat#10]
Hi, 
When trying to compile with make, I see the following error: 
gcc -O -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64 -I./inc -I./htslib -c -o https.o lib/https.c
lib/https.c:6:10: fatal error: 'openssl/ssl.h' file not found
#include "openssl/ssl.h"
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [https.o] Error 1

I am following installation instructions from Nature Protocols volume 15, pages1098–1131(2020), (link: https://www.nature.com/articles/s41596-019-0279-7#Sec23), on a MacOS Version 10.13.6, if this information helps. 
Any help or thoughts would be greatly appreciated! Maybe I need to adjust the paths for openssl? but i'm not sure how to do it properly. Thank you

**Comment by icebert** [comment]
Hi Kjran,

You can install openssl following these links:

https://stackoverflow.com/questions/35129977/how-to-install-latest-version-of-openssl-mac-os-x-el-capitan

https://medium.com/@timmykko/using-openssl-library-with-macos-sierra-7807cfd47892

**Comment by kjran** [comment]
Thanks for the links!  I'll give these a try!

**Comment by andrewguy** [comment]
For anyone else with a similar issue using Linux, I had to install `libssl-dev` to fix this error under Ubuntu 18.04 (`sudo apt update && sudo apt install libssl-dev`). Installing `openssl` did not seem to be enough.

**Comment by kjran** [comment]
Thanks!  I will give this a try

**Comment by icebert** [comment]
Now pblat support installing from bioconda.
