### ISSUE TITLE
Internal error jkOwnLib/trans3.c 71

### ISSUE THREAD

**Issue by NullModel** [icebert/pblat#11]
Please note source files for this example available at: [https://genome-test.gi.ucsc.edu/~hiram/pblat/](url)

Tried command:
`time ./pblat -threads=2 -noHead -q=rnax -t=dnax -mask=lower \
   GCF_901000725.2_fTakRub1.2.2bit refSeqMrna.fa \
       GCF_901000725.2_fTakRub1.2.xenoRefGene.psl
`

Failure:
`Loaded 384126662 letters in 128 sequences
Blatx 128 sequences in database, 237906 files in query
Internal error jkOwnLib/trans3.c 71

real    591m4.026s
user    1085m0.023s
sys     16m38.805s
`

See example files:
`-rw-rw-r-- 1 997165206 Aug  9  2019 refSeqMrna.fa

-rw-rw-r-- 1 109199773 Jan 15 07:10 GCF_901000725.2_fTakRub1.2.2bit

-rwxrwxr-x 1   1062472 May  1 15:28 pblat

-rw-rw-r-- 1       171 May  3 12:27 run.sh

-rw-rw-r-- 1       182 May  3 12:28 run.log
`

Running on system:

`file pblat

pblat: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=980da6786dfd0811359b238fa0e4c1d955ece3b1, not stripped
`

**Comment by NullModel** [comment]
Can anyone duplicate this issue ?

**Comment by icebert** [comment]
Thank you very much for the feedback. I fixed this in the new release. Please compile with the latest code or install with bioconda.
