### ISSUE TITLE
[malloc] error with protein query and DNA database

### ISSUE THREAD

**Issue by edgardomortiz** [icebert/pblat#13]
I have just installed `pblat v.2.3` through bioconda in Mac. When trying to replicate `blat` results with the command:
```
pblat -t=dnax -q=prot -noHead  -minIdentity=54 -minScore=15 assembly_dna.fasta ref_proteins.faa output.psl
```
The following error occurs:
```
pblat(4387,0x7fff8ea61380) malloc: *** error for object 0x7ff72fade900: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Loaded 26764612 letters in 39673 sequences
Blatx 39673 sequences in database, 4782 files in query
...done in 13 seconds
```
The `.psl` is produced but with roughly as half the hits as the ones that are obtained by `blat`
Am I missing something? Any help is appreciated

Edgardo

**Comment by icebert** [comment]
I fixed this in the new release v2.5. Please update with bioconda.
