### ISSUE TITLE
installation issue (make: *** [all] Error 1)

### ISSUE THREAD

**Issue by zhongzheng1999** [icebert/pblat#19]
Hello
I have been unable to successfully install pblat due to some ERROR.
I enter the source code directory in terminal and issue the "make" command, the following error message has appeared.

> gcc -O -Wall  -o pblat blat.o jkOwnLib.a jkweb.a htslib/libhts.a  -lm -lpthread -lz -lssl -lcrypto
jkweb.a(https.o): In function `openSslInit':
https.c:(.text+0xb1): undefined reference to `OPENSSL_init_ssl'
https.c:(.text+0xc0): undefined reference to `OPENSSL_init_crypto'
https.c:(.text+0xd4): undefined reference to `OPENSSL_init_crypto'
jkweb.a(https.o): In function `netConnectHttpsThread':
https.c:(.text+0x136): undefined reference to `TLS_client_method'
https.c:(.text+0xaea): undefined reference to `TLS_client_method'
collect2: error: ld returned 1 exit status
make: *** [all] Error 1

I checked my OpenSSL:

> [yugy.life@login02 lib]$pwd
/usr/local/openssl/lib
[yugy.life@login02 lib]$nm -D libcrypto.so | grep OPENSSL_init
0000000000195ff0 T OPENSSL_init
0000000000185730 T OPENSSL_init_crypto
[yugy.life@login02 lib]$nm -D libssl.so | grep OPENSSL_init
                 U OPENSSL_init_crypto
00000000000361e0 T OPENSSL_init_ssl
[yugy.life@login02 lib]$nm -D libssl.so | grep TLS_slient_method
[yugy.life@login02 lib]$nm -D libssl.so | grep TLS_client_method
000000000001fdf0 T DTLS_client_method
000000000001fd10 T TLS_client_method
[yugy.life@login02 lib]$

**Comment by icebert** [comment]
Maybe you can try:

`export LD_LIBRARY_PATH=/usr/local/openssl/lib:$LD_LIBRARY_PATH`

**Comment by Zhongzheng99** [comment]
Thank you for your reply. I tried and it didn't work.

**Comment by icebert** [comment]
That’s weird. Maybe it’s due to the version of openssl. Another way is to install using conda.
