### ISSUE TITLE
Reading query from list

### ISSUE THREAD

**Issue by martinbaste** [icebert/pblat#2]
I noticed that pblat doesn't support reading query files from a file containing a list.
The strange thing is that I used a file containing query files and pblat used only the first query file and then stopped. 

In order to avoid confusion, I think pblat should either:
- Read query files from a list like blat does. (Probably the best, even using databases from a list is supported)
- Not read any query files from a list and notify the user that the query is not valid.

The current behavior is confusing because the user can think that pblat used all query files from the list when it only used one.

**Comment by icebert** [comment]
Hi Martin,

Thank you very much for  you suggestions. I will change the code accordingly to make this clear.

Best regards,

Meng
