### ISSUE TITLE
Time usage is the same between normal blat and pblat

### ISSUE THREAD

**Issue by tao-bioinfo** [icebert/pblat#3]
I use 24 threads. There are 24 tmp files when running, but all blank.
Finally, pblat get identical result with  normal blat. But the  time usage is the same. Both ~700s
Am I getting something wrong?

**Comment by icebert** [comment]
Hi billet, did you run pblat with protein sequences? Currently pblat only supports querying DNA/RNA sequences in multi-thread mode. For protein sequences, it is still single threaded.

**Comment by tao-bioinfo** [comment]
@icebert No, I run pblat using DNA sequences. As the reference genome is large, I've no idea how to show you the test data

**Comment by icebert** [comment]
Another possible situation is that the number of query sequences is small, so most of the time consumed is loading the references. Loading the references is single threaded. When the number of query sequences is large, the difference of the time consumption would be more obvious.

**Comment by tao-bioinfo** [comment]
Yes, you are right. I only use one query sequence. The query sequence results from BAC sequencing and is very long (~70kb). Do you have any good iead to accerate such BLAT?

**Comment by icebert** [comment]
I think it's very hard to accelerate the alignment of single sequence under the blat framework.

**Comment by yuzhenpeng** [comment]
> Yes, you are right. I only use one query sequence. The query sequence results from BAC sequencing and is very long (~70kb). Do you have any good iead to accerate such BLAT?

You can split the reference using faSplit, then run pblat by parallel.
