### ISSUE TITLE
empty tmp files

### ISSUE THREAD

**Issue by gbdias** [icebert/pblat#8]
Hi,

I am using pblat v2.1 to align two genomes (200 Mb, 6 chromosomes each). I gave it 28 threads and 200 Gb RAM, and all but one of the 28 `.psl.tmp.x` temp files are empty. The software seems to be running since CPU time is increasing faster than clock time but I don't see anything being written to the files.

Is this normal behavior?

Thanks,
Gui

**Comment by icebert** [comment]
The output may be cached. You can try with a small input and compare the finial output with single thread results. If they are identical, your installation is correct.
